### ISSUE TITLE
v0.2.0 Mobile touchEvents

### ISSUE THREAD

**Issue by bfourgeaud** [formkit/drag-and-drop#105]
In v0.2.0 the mobile items are broken in multiple ways :
- No iteractivity on items, if I have a button inside my item, it won't be clickable _(worked on v0.1.6)_
- `longPressClass` is not applied to items _(longTouchClass worked on v0.1.6)_
- Can't drag items on mobile screens, with or without `longPress` enabled _(worked  with flaws on v0.1.6)_

Here is my code :  

```.tsx
// draggable.tsx

import { ComponentProps, ReactNode, useEffect, useTransition } from "react"
import { useDragAndDrop } from "@formkit/drag-and-drop/react"
import {
  animations,
  handleEnd as coreHandleEnd,
  DragState,
  SynthDragState,
} from "@formkit/drag-and-drop"
import { cn } from "@/lib/utils"

type Props<T> = {
  onChange?: (data: T[]) => Promise<void> | void
  items: T[]
  children: (item: T) => ReactNode
  dragHandle?: string
  checkSame?: (curr: T[], changed: T[]) => boolean
} & Omit<ComponentProps<"div">, "children" | "onChange">

const compareArrays = <_, T>(a: T[], b: T[]) =>
  a.length === b.length && a.every((element, index) => element === b[index])

export const Draggable = <_, T>({
  onChange,
  items,
  children,
  dragHandle,
  checkSame = compareArrays,
  ...props
}: Props<T>) => {
  const [pending, startTransition] = useTransition()

  const onDragEnd = async (data: DragState<T> | SynthDragState<T>) => {
    const parent = data.currentParent.el
    const newData = data.currentParent.data.getValues(parent)
    const isSame = checkSame(items, newData)

    !isSame && startTransition(async () => await onChange?.(newData))
    coreHandleEnd(data)
  }

  const [parent, listItems, setValues, updateConfig] = useDragAndDrop<
    HTMLDivElement,
    T
  >(items, {
    dragHandle,
    plugins: [animations()],
    handleEnd: onDragEnd,
    longPress: true,
    longPressClass: "shadow-xl peer:opacity-50",
    draggingClass: "opacity-50 bg-muted border border-blue-500",
    dropZoneClass: "bg-muted border-dashed relative",
    //nativeDrag: true,
  })

  useEffect(() => {
    setValues(items)
  }, [items, setValues])

  return (
    <div
      ref={parent}
      className={cn(props.className, {
        "opacity-50 animate-pulse pointer-events-none": pending,
      })}
      tabIndex={-1}
      {...props}
    >
      {listItems.map(children)}
    </div>
  )
}
```

```.tsx
// items.tsx

export function Items({ items }: Props) {
  const handleChange = async (data: LitItem[]) => {
    await reorderList(data)
    toast.success("List updated")
  }

  return (
    <Draggable
      items={items}
      onChange={handleChange}
      dragHandle=".drag-handle"
      className="flex flex-col gap-2"
    >
      {(item) => <ListItem key={item.id} item={item} />}
    </Draggable>
  )
}
```

```.tsx
// list-item.tsx

function ListItem({ item}: { item: LitItem }) {
  return (
    <div
      tabIndex={0}
      className="relative peer border rounded-md p-2 flex items-start justify-between gap-4 bg-card focus:border-blue-500 focus-visible:border-blue-500"
    >
      <div className="flex items-start gap-4">
         {...}
      </div>
      <div className="flex flex-col items-center gap-2">
        <button className="cursor-grab drag-handle" tabIndex={-1}>
          <GripVertical className="size-4 text-muted-foreground" />
          <span className="sr-only">Move item</span>
        </button>
        <button tabIndex={-1}>
          <Edit className="size-4" />
          <span className="sr-only">Edit Item</span>
        </button >
      </div>
    </div>
  )
}
```

**Comment by sashamilenkovic** [comment]
@bfourgeaud Hey there! Apologies for these regressions. Yes, I can confirm I'm seeing longPress and longPressClass not having any effect. I'm also seeing some issues when using drag handles which I believe is the cause of this, "Can't drag items on mobile screens, with or without longPress enabled (worked with flaws on v0.1.6)". I'll be working on all of this next.

**Comment by bfourgeaud** [comment]
Hello thanks for your quick response.  

I've tried without `dragHandle` : 
- The drag works on mobile (and has quite the improvement when working in overflowed containers).
- The events inside the dragItem (buttons etc) still have no effect
- The `longPress` & `longPressClass` still don't have any effect

I hope you'll find the source of the problem ;)

**Comment by sashamilenkovic** [comment]
@bfourgeaud Okay, can you when you have the chance check out v0.2.2. Drag. handles should be working now. Buttons within a draggable item should still have click fired, and the long press and longPressClasses should be working again. I'll leave this open until I hear back.

**Comment by bfourgeaud** [comment]
I just tested out v0.2.2, and yes `longPress`, `longPressClass` and dragging on mobile working again !
But still having trouble with click fired inside item. I'm doing a reproduction now, updating comment when done.

**Comment by bfourgeaud** [comment]
Here is my repro : https://github.com/bfourgeaud/formkit-dnd-issue105-repro

* On mobile the Edit button cannot be clicked
* On mobile, the text cannot be expanded onClick
* When switching from desktop to mobile, the DND feature isn't working, has to refresh. (Either way)
* When longPress=true, on mobile you can still drag items without longPressing

**Comment by sashamilenkovic** [comment]
@bfourgeaud Perfect, I will take a look.

**Comment by sashamilenkovic** [comment]
@bfourgeaud Hey there! Check out v0.2.3. I believe these have been addressed, but again, I'll leave this open until I hear back from you. Really appreciate the reproduction/instructions; you made it easy for me 👍

**Comment by bfourgeaud** [comment]
@sashamilenkovic 🎉 It works perfectly, thank you !! And no problem for the reproduction, it's the least I could do !

**Comment by nmhungdev** [comment]
@sashamilenkovic
It seems it doesn't work with `"@formkit/drag-and-drop": "^0.2.6"`.

**Comment by hungify** [comment]
Hey @bfourgeaud, @sashamilenkovic !
After tested on your  repro : [bfourgeaud/formkit-dnd-issue105-repro](https://github.com/bfourgeaud/formkit-dnd-issue105-repro)
Here quick response
- The `longPressDuration` and `longPress` functions work correctly on iOS (iPhone 15, iOS 17.2, Simulator).
- The `longPressDuration` feature seems inconsistent on the Samsung A51. While it functions as expected in some situations, there are frequent instances where it fails to register the long press action altogether.

**Comment by sashamilenkovic** [comment]
@hungify hey there! Would you mind filing a new issue for this?

**Comment by hungify** [comment]
Hey @sashamilenkovic !
Here quick response

1. nativeDrag is true
```
{
    nativeDrag: true,
}
```
Works, but issue-1 persists.

2. nativeDrag = true and longPress = true
```
{
    nativeDrag: true,
	longPress: true,
    longPressDuration: 100,
}
```
PC: Broken (drag initiates immediately).
Android: Works properly.
iOS: Does not work.
Overall: issue-1 persists.

3. nativeDrag = false
```
{
    nativeDrag: false
}
```
Works, but issue-1 persists.


4. nativeDrag = false and longPress = true
```
{
    nativeDrag: false
}
```
PC: Works in some cases but frequently fails to drag the item.
Mobile: Functions correctly.
Overall: issue-1 persists.
Note:
•	Issue-1: The render position of the drag preview on mobile devices (both Android and iOS) is incorrect during drag initialization.
	•	This is noticeable with transition: transform 0.3s ease used for debugging.
	•	Link for observation: [GitHub Attachment](https://github.com/user-attachments/assets/08bd4e76-2b9e-4645-9fd4-6c9ab5dd1715)

Let's try on my repo:
- https://formkit-dnd.netlify.app
- https://github.com/hungify/dnd-formkit

**Comment by hungify** [comment]
Hey, @sashamilenkovic!
After spending a lot of time debugging, I noticed that the setTimeout callback in HandleLongPress sometimes gets triggered and sometimes doesn’t on Android devices. However, it works perfectly on PC Chrome DevTools.

**Comment by sashamilenkovic** [comment]
@hungify Hey there! Apologies, I will take a look at this. Appreciate you digging into this yourself.
