### ISSUE TITLE
Bug Report: Parsing Error in useDragAndDrop Hook

### ISSUE THREAD

**Issue by DavidNavarroSaiz** [formkit/drag-and-drop#13]
I encountered a parsing error when using the useDragAndDrop hook from the @formkit/drag-and-drop/react package. 
The error occurs when attempting to destructure the return value of the hook in a single line.
Steps to Reproduce:
Install the @formkit/drag-and-drop package.
Import and use the useDragAndDrop hook in a React component.
Attempt to destructure the return value of the hook in a single line.
Run the application or build process.

import React from "react";
import { useDragAndDrop } from "@formkit/drag-and-drop/react";

export function MyComponent() {
  const todoItems = ["Schedule perm", "Rewind VHS tapes", "Make change for the arcade", "Get disposable camera developed", "Learn C++", "Return Nintendo Power Glove"];
  const doneItems = ["Pickup new mix-tape from Beth"];

  const todoDragAndDrop = useDragAndDrop<HTMLUListElement, string>(
    todoItems,
    { 
      group: "todoList",
      sortable: false
    }
  );
  const doneDragAndDrop = useDragAndDrop<HTMLUListElement, string>(
    doneItems,
    { 
      group: "todoList",
      sortable: false
    }
  );

  const todoList = todoDragAndDrop[0];
  const todos = todoDragAndDrop[1];
  const doneList = doneDragAndDrop[0];
  const dones = doneDragAndDrop[1];

  return (
    <div className="kanban-board">
      <ul ref={todoList}>
        {todos.map(todo => (
          <li className="kanban-item" key={todo}>
            {todo}
          </li>
        ))}
      </ul>
      <ul ref={doneList}>
        {dones.map(done => (
          <li className="kanban-item" key={done}>
            {done}
          </li>
        ))}
      </ul>
    </div>
  );
}

![image](https://github.com/formkit/drag-and-drop/assets/32474368/2b75dd26-6301-47e3-9ec2-2524e886a460)

**Comment by justin-schroeder** [comment]
Looks like your file is a jsx not a tsx. Remove the type annotation (the part in the angle brackets) and you should be good to go.
