### ISSUE TITLE
Nested dragAndDrop not working?

### ISSUE THREAD

**Issue by suspiciousRaccoon** [formkit/drag-and-drop#19]
I'm trying to build a simple trello-like kanban board and would like to have sorting and dnd in both the tasks and lists, however, I'm not able to select or sort the child elements. I'm not sure if this is a limitation of the library or a misconfiguration from my part. 
If this is something supported I'd suggest adding an example to the docs.
Example in [CodeSandbox](https://codesandbox.io/p/github/suspiciousRaccoon/formkit-drag-and-drop-nested-kanban-board/main?import=true&layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clt3fy0rs0006206ag841e63g%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clt3fy0rs0002206av10bkowm%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clt3fy0rs0004206agwhleftz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clt3fy0rs0005206atujzvnpr%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clt3fy0rs0002206av10bkowm%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt3fy0rs0001206absmm4gwa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clt3fy0rs0002206av10bkowm%2522%252C%2522activeTabId%2522%253A%2522clt3fy0rs0001206absmm4gwa%2522%257D%252C%2522clt3fy0rs0005206atujzvnpr%2522%253A%257B%2522id%2522%253A%2522clt3fy0rs0005206atujzvnpr%2522%252C%2522activeTabId%2522%253A%2522clt3g0h8q00ph206aadmy3k2x%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clt3g0h8q00ph206aadmy3k2x%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clt3fy0rs0004206agwhleftz%2522%253A%257B%2522id%2522%253A%2522clt3fy0rs0004206agwhleftz%2522%252C%2522activeTabId%2522%253A%2522clt3fyo9600b2206abhp9f7ut%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt3fy0rs0003206a93km2m21%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clt3fy1hg000sdif83unq1ns7%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Fjavascript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522clt3fymom0050206a2ofecr0z%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clt3fyo9600b2206abhp9f7ut%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
```js
const dataDict = {
  board: {
    lists: [
      {
        name: "first list",
        id: "listId1",
        tasks: [
          { id: "listId1 11", name: "1 one" },
          { id: "listId1 12", name: "1 two" },
          { id: "listId1 13", name: "1 three" },
        ],
      },
      {
        name: "second list",
        id: "listId2",
        tasks: [
          { id: "listId2 21", name: "2 one" },
          { id: "listId2 22", name: "2 two" },
          { id: "listId2 23", name: "2 three" },
        ],
      },
    ],
  },
};

function App() {
  const [parent, lists] = useDragAndDrop(dataDict.board.lists, {
    plugins: [animations()],
    dragHandle: ".list-handle",
  });
  const style = { display: "flex", gap: "30px", margin: "auto" };
  return (
    <div ref={parent} style={style}>
      {lists.map((list) => {
        return <List key={list.id} data-label={list.id} {...list} />;
      })}
    </div>
  );
}

const List = ({ name, tasks }) => {
  const [parent, tasksList] = useDragAndDrop(tasks, {
    group: "board",
    draggable: (el) => {
      return el.id !== "no-drag";
    },
  });
  return (
    <div ref={parent}>
      <h1 id="no-drag" className="list-handle">
        {name}
      </h1>
      {tasksList.map((task) => (
        <Task key={task.id} {...task} />
      ))}
    </div>
  );
};

const Task = ({ name }) => {
  return <div>{name}</div>;
};

```

**Comment by sashamilenkovic** [comment]
@suspiciousRaccoon Thank you for pointing this out. This should now be working at v0.0.23
