### ISSUE TITLE
Types for parentRef

### ISSUE THREAD

**Issue by mire-toctoc** [formkit/drag-and-drop#26]
Does the drag and drop functionality just accepts the use of `<ul>` and `<li>` tags?

I'm currently having an issue related to the parent definition, where the error `Type 'MutableRefObject<HTMLUListElement>' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 290 more.` is present. I've tried different definition types for my parentRef, but is not working. Before this definition, I was trying to use a `<div>`, but it has the same problem.

Please, give us more information about expected types in both 

> useDragAndDrop

 and 

> dragAndDrop

 hooks, so users can avoid having this kind of issues

My implementation:
```
const parentRef = React.useRef() as React.MutableRefObject<HTMLUListElement>;
	const [imagesList, setImagesList] = useState(images)
		dragAndDrop({
			parent: parentRef,
			state: [imagesList, setImagesList]
			})

```

**Comment by justin-schroeder** [comment]
no

**Comment by malshoff** [comment]
you can use parentRef.current, but you're still going to have issues. I've never gotten this to work properly with React unless I use nothing but the demo ul/li implementation with the useDragAndDrop hook. The only documentation is a 3 line snippet that doesn't even show full usage, so I'd recommend @hello-pangea/dnd library
