### ISSUE TITLE
Cannot use index as `:key`

### ISSUE THREAD

**Issue by distantnative** [formkit/drag-and-drop#28]
When using the following setup in Vue

```html
<template>
	<div ref="parent">
		<template v-for="(item, itemIndex) in items">
			<div :key="itemIndex">{{ item.foo }}</div>
		</template>
	</div>
</template>
```

the list becomes unresponsive after starting to drag one element. It moves one position further, then is stuck.

I would assume this has to do with the index already changing before the drag has been completed and thus Vue stumbling over what is which element.

Anything that can be done about this? 

Thanks a lot for your work! Trying to replace the old vuedraggable we use in https://github.com/getkirby/kirby with this - and getting far but not fully working yet 🤞

**Comment by justin-schroeder** [comment]
Yes. Thats correct — you should never use an index as a key in any reactive framework actually — it is a `no-op`. Related reading:

https://vueschool.io/articles/vuejs-tutorials/tips-and-gotchas-for-using-key-with-v-for-in-vue-js-3/
https://dev.to/shiv1998/why-not-to-use-index-as-key-in-react-lists-practical-example-3e66
https://kuldipem.medium.com/say-no-to-array-index-as-key-in-react-my-approaches-to-tackle-it-that-you-can-use-51153bfa8901

Just use a unique index and you’ll be good to go ❤️
