### ISSUE TITLE
Why doesn't it disable draggable?

### ISSUE THREAD

**Issue by castrogarciajs** [formkit/drag-and-drop#34]
Hello team formkit,

I'm trying to disable `boardFirst` so that `board Second` doesn't receive more elements but it's not working... I don't know what I'm doing wrong.

Thank you for reading

# Guide

## Code

![code](https://github.com/formkit/drag-and-drop/assets/116913262/99aedfc0-3654-4deb-a2ee-1f8cdc35a54d)

## Reproduction

The problem is file `src/routes/sum.tsx`

https://stackblitz.com/~/github.com/labs-company/mathematics

**Comment by sashamilenkovic** [comment]
@castrogarciajs Firstly, very cool app! Do you want to give v0.0.29 a shot?

**Comment by sashamilenkovic** [comment]
For your example, you may need to apply `user-drag: none` to avoid dragging of the underlying images.

**Comment by castrogarciajs** [comment]
Thank You @sashamilenkovic, It is an application for children to learn arimetic with tens... Of course I will try version v0.29.0

**Comment by castrogarciajs** [comment]
@sashamilenkovic It worked, that's great!!!... You just saved my life, I thank you very much.

**Comment by sashamilenkovic** [comment]
@castrogarciajs Thank you for reporting the issue! Let me know if you have any other issues.
