### ISSUE TITLE
Touch mode: internal dragged element copy not being removed from the DOM

### ISSUE THREAD

**Issue by wesharper** [formkit/drag-and-drop#36]
I've noticed this intermittently while QA testing my own app and it appears that any interruption that prevents the drag-end event from firing causes the issue. However, right clicking while dragging in responsive mode in the dev tools is the easiest way I've found to reproduce the issue reliably.

https://github.com/formkit/drag-and-drop/assets/13283469/4beb93b0-696b-461d-b737-533fa73fe5be

**Comment by sashamilenkovic** [comment]
@wesharper At version 0.0.33 right-clicking while dragging in responsive mode will no longer bring up the context menu, leading to the cancellation of the dragend event. I'll close this for now, but let us know if you are able to trigger these "interruptions" in another way.
