### ISSUE TITLE
Jittery behavior when hovering sublings

### ISSUE THREAD

**Issue by Lazerproof** [formkit/drag-and-drop#39]
Hi. 

I got jittery behavior:

![chrome_wGug5QTadE](https://github.com/formkit/drag-and-drop/assets/5707348/1e17bbe5-efad-4f2a-98ec-53ec6c7395c5)

There is the reproduction with formkit drag-and-drop and vuedraggable. As you can see vuedraggable can handle such a case without glitching. 

https://codesandbox.io/p/sandbox/fk-drag-touch-repro-forked-hfr8dq

**Comment by sashamilenkovic** [comment]
@Lazerproof Having a hard time replicating with your reproduction. Could you tell me which browser/device you are using?

**Comment by Lazerproof** [comment]
@sashamilenkovic  
Win: 11
Chrome 122.0.6261.129 (Official Build) (64-bit)

Got the same behavior in Chrome and Brave browser on Google Pixel.

There are two examples in my reproduction. The first (upper) is on vuedraggable, and the second (lower) is on formkit/drag-and-drop.

Try to move 'Pet Shop Boys' over 'Duran Duran' on the second example.

**Comment by Lazerproof** [comment]
Example from Microsoft Edge Version 122.0.2365.92

![msedge_D8LTom1lJO](https://github.com/formkit/drag-and-drop/assets/5707348/72c77f69-4caa-42b1-9520-7f73bf350745)

**Comment by sashamilenkovic** [comment]
@Lazerproof Perfect, I will look into this

**Comment by sashamilenkovic** [comment]
@Lazerproof Would you mind taking a look at v0.0.30 and see if that resolves the issue?

**Comment by Lazerproof** [comment]
@sashamilenkovic Yes, looks like it resolves. Thanks!
