### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by akaratsuba** [formkit/drag-and-drop#40]
There seem to be several missing pieces of documentation:

- How do I use this with Vue?
- How do I use this with Svelte?
- How do I update the settings after creating it?
- How do I get `setState` in React?
- How do I add something to a list of draggable items?
- The docs say you can create custom plugins but only describes 1 plugin. Where is the API for doing this?

Cool project!

**Comment by valentinoPereira** [comment]
I have async data coming from my database, how to attach event handlers and get data of the element being dragged from and to position along with ids?

**Comment by sashamilenkovic** [comment]
I believe that most of this have been addressed. @aarjithn Would you mind filing an issue if there's anything else you see missing/needs more attention? @valentinoPereira Check out the `onSort` and `onTransfer` parent event listeners: https://drag-and-drop.formkit.com/#parent-events
