### ISSUE TITLE
z-index at elements after drag does not disappear, in vue

### ISSUE THREAD

**Issue by Jerd0** [formkit/drag-and-drop#41]
z-index at elements after drag does not disappear, in vue

https://stackblitz.com/edit/vitejs-vite-xghckt?file=src%2FApp.vue

https://github.com/formkit/drag-and-drop/assets/48857511/c21dbc94-9b4a-4646-a726-33f894b0c9c4

it seems to me that z-index should be removed automatically after the end of a drag event.

**Comment by sashamilenkovic** [comment]
@Jerd0 Hey there! When you define `handlEnd`, you are actually overriding the core `handleEnd` event. The way to do this would be to import the original `handleEnd` and invoke it after: https://stackblitz.com/edit/vitejs-vite-t7bzxw?file=src%2Fcomponents%2Ftest.vue. We plan to implement some system of emitting events in the future, so you don't need to worry about overriding existing events. I'll close this for now but please let me know if you have any other questions.

**Comment by OsirisFrik** [comment]
Hi, I have the same issue

I try with `handleEnd` function but don't work

![Image](https://github.com/user-attachments/assets/46c7af1b-72cd-4098-a5d0-e1ad192a7991)

![Image](https://github.com/user-attachments/assets/8359ec93-e066-46bd-842e-dbced2ed8647)

https://github.com/user-attachments/assets/b0e84dfa-7cc7-45a4-9ede-75d521b0b92c
