### ISSUE TITLE
Draggin via touch breaks the display

### ISSUE THREAD

**Issue by Techn1c4l** [formkit/drag-and-drop#44]
When doing drag and drop using mouse, it works just fine.

However, once switched to a touch device view in a browser, the display is broken. Strangely, it also won't allow any right click on the page on any element afterwards. After checking the DOM, it seems like the copy of the dragged node is added to the DOM, but never removed.

Switching back to the mouse device doesn't fix it.

This is how it looks like.

![image](https://github.com/formkit/drag-and-drop/assets/80050457/53f42ab2-868f-408c-a560-91b8b9fb8def)

Tested both on Chrome 122.0.6261.129 and Firefox 123.0.1.

P.S. Can we get an option to disable opacity on a dragged node?

**Comment by sashamilenkovic** [comment]
@Techn1c4l Hey there! Would you mind showing a reproduction of how you get into the broken state? I am having a hard time replicating on my end.

**Comment by Techn1c4l** [comment]
> @Techn1c4l Hey there! Would you mind showing a reproduction of how you get into the broken state? I am having a hard time replicating on my end.

I tried to reproduce it on the StackBlitz, but it works just fine there. Guess I'll have to look into my project a bit more.

**Comment by Leorio21** [comment]
Hi !
I have the same problem, it's appear when using handleEnd function
![image](https://github.com/formkit/drag-and-drop/assets/102737876/ce44c096-66e0-4b32-b22f-7ac627982959)

code : https://github.com/Leorio21/DragAndDropBug

deploy : https://drag-and-drop-bug.vercel.app/
