### ISSUE TITLE
Drag nodes jump back and forth if we try to drag a smaller node over a larger node

### ISSUE THREAD

**Issue by Jerd0** [formkit/drag-and-drop#45]
Drag nodes jump back and forth if we try to drag a smaller node over a larger node

try dragging the first node as shown in the video.
https://stackblitz.com/edit/vitejs-vite-xghckt?file=src%2FApp.vue

https://github.com/formkit/drag-and-drop/assets/48857511/7d882677-cb41-4a31-a95c-cac5646baaad

**Comment by sashamilenkovic** [comment]
@Jerd0 Try updating to the latest version (v0.0.33). Here's updated version with it working. https://stackblitz.com/edit/vitejs-vite-g9gjx6?file=src%2Fcomponents%2Ftest.vue

**Comment by sashamilenkovic** [comment]
An additional note, when dealing with elements that vary in size greatly, you might want to mutate the "threshold" like so: https://stackblitz.com/edit/vitejs-vite-z1zxry?file=src%2Fcomponents%2Ftest.vue (just personal preference, I think it feels a bit more natural).

**Comment by Jerd0** [comment]
@sashamilenkovic yep, I'm already using 0.0.33, and thanks for the threshold idea, that should be helpful

**Comment by Jerd0** [comment]
@sashamilenkovic yep, I'm already using 0.0.33, and thanks for the threshold idea, that should be helpful
