### ISSUE TITLE
Bug: touch/mobile devices don't scroll vertically at drag boundary

### ISSUE THREAD

**Issue by wesharper** [formkit/drag-and-drop#48]
I have a table that contains draggable items that takes up about 25vh. On desktop, dragging to the overflow boundary scrolls the table. On mobile/responsive/touch, it does not.

**Comment by sashamilenkovic** [comment]
@wesharper v0.0.37 has an assortment of scroll bug fixes. Is this fixed for you? And if not, can you provide a reproduction I can take a look at?

**Comment by wesharper** [comment]
Looks like it works, thanks @sashamilenkovic!
