### ISSUE TITLE
Custom dropZoneClass is not removed when dragging between two columns (groups)

### ISSUE THREAD

**Issue by OliverArthur** [formkit/drag-and-drop#50]
When working with two columns ("groups"), I've encountered an issue where the custom dropZoneClass is not removed upon dragging and dropping between the columns. However, I've noticed that when I sort an item within the same column or group, the custom class is properly removed.

I attempted to address this by implementing the following code:

```typescript
handleEnd: data => {
    if (data.targetData.node) {
        data.targetData.node.el.classList.remove("is-dragging-over");
    }
}
```

Unfortunately, this solution didn't resolve the issue.

Attached is a video demonstrating the problem, along with a link to the relevant code.

Link with the code -> https://stackblitz.com/edit/vitejs-vite-4fm42b?file=src%2FApp.vue

##### Video
https://github.com/formkit/drag-and-drop/assets/4415265/1505bf8e-7407-47dc-8a09-79d81237d574

**Comment by sashamilenkovic** [comment]
@OliverArthur Talked about this here: [46](https://github.com/formkit/drag-and-drop/issues/46).

"when you define handleEnd, you are actually overriding the core event handler itself. The idea is to import the original handleEnd and reinvoke it before or after whatever logic you are trying to add on:"

Here's a fork of your playground: https://stackblitz.com/edit/vitejs-vite-5g4gdn?file=src%2Fcomponents%2FSortable.vue

**Comment by carlosvaldesweb** [comment]
@sashamilenkovic I think that it should be documented

> when you define handleEnd, you are actually overriding the core event handler itself. The idea is to import the original handleEnd and reinvoke it before or after whatever logic you are trying to add on:
