### ISSUE TITLE
Bug: scrolling in an overflow container using touch doesn't work

### ISSUE THREAD

**Issue by wesharper** [formkit/drag-and-drop#51]
I have a scrollable container with a bunch of sortable elements that have drag handles. I can scroll with the mouse, but not on touch devices with drag.

Video:

https://github.com/formkit/drag-and-drop/assets/13283469/44993570-946a-4ad7-a9d9-3997eb3f9abd

Repro:
https://codesandbox.io/p/sandbox/fk-drag-touch-repro-forked-fy4pz9

**Comment by sashamilenkovic** [comment]
@wesharper This should be resolved at v0.0.37
