### ISSUE TITLE
Bug on multi-select

### ISSUE THREAD

**Issue by Syed-Sheharyar** [formkit/drag-and-drop#6]
There's a bug in the multi-select where any item you click or start a drag on remains selected, so when you drag another item, it brings all the previously clicked items as well

[https://imgur.com/a/82W97sn](https://imgur.com/a/82W97sn)
I click-dragged character1.txt but the other came together. This only happens after you select an item, before that click-drag works fine

**Comment by sashamilenkovic** [comment]
@Syed-Sheharyar This should be fixed at v0.0.21
