### ISSUE TITLE
Drag and drop in a table

### ISSUE THREAD

**Issue by Powershooter83** [formkit/drag-and-drop#60]
Hello everyone, I'm not quite sure if this is the right place for this. But anyway:

Is there a way to implement the whole thing with a table? 
I have not yet managed to move individual rows by drag and drop.

Thanks for the help!

**Comment by sashamilenkovic** [comment]
@Powershooter83 there's a stakblitz example here https://github.com/formkit/drag-and-drop/issues/37#issue-2187022745 you could take a look at.
