### ISSUE TITLE
typo in doc

### ISSUE THREAD

**Issue by haoyun** [formkit/drag-and-drop#72]
https://github.com/formkit/drag-and-drop/blob/d23853bfe84c7c52bdb372364550362e51af0517/docs/components/Section/GettingStarted.vue#L73

should be `values`, accodring to 

https://github.com/formkit/drag-and-drop/blob/d23853bfe84c7c52bdb372364550362e51af0517/src/vue/types.ts#L8

**Comment by sashamilenkovic** [comment]
@haoyun Thank you. This has been merged.
