### ISSUE TITLE
Please Add PointerEvents API support for external mouse / touchpad on tablet support / iPad with Magic Keyboard Support

### ISSUE THREAD

**Issue by agotfredsen82** [formkit/drag-and-drop#77]
Hi. Love your framework but as it does not have support for PointerEvents such as

addEventListener("pointerdown", (event) => {});

addEventListener("pointermove", (event) => {});

addEventListener("pointerenter", (event) => {});

addEventListener("pointerover", (event) => {});

etc etc it does not work at all when using external mouse, Magic Keyboard with touchpad or remote controlling a iPad from a Mac .

Please add PointerEvents API support so it functions correctly, it feels it´s not that much work to add to have it function properly .

Best Regards

**Comment by sashamilenkovic** [comment]
@agotfredsen82 That's interesting. Yes, we are currently not using the PointerEvents API and instead are differentiating between Drag and Touch Events. Definitely something we can look into modifying in the future. However, I also use a mac with a touch pad and have never run into this issue. Is there some sort of reproduction you can produce or additional details you can give about the issue you're having?

**Comment by sashamilenkovic** [comment]
@agotfredsen82 Oh gotcha, I misunderstood. I thought you meant it wasn't working on your mac computer with a trackpad. Yes, this is something we'll look into. Thanks for letting us know!

**Comment by sashamilenkovic** [comment]
@agotfredsen82 apologies for the late reply; I started working on this last night and made a good bit of progress. No timetable but hopefully this will be released sooner rather than later.

**Comment by sashamilenkovic** [comment]
@agotfredsen82 This has been implemented at `v0.2.0`
