### ISSUE TITLE
The number of enabled nodes does not match the number of values. 

### ISSUE THREAD

**Issue by valentinoPereira** [formkit/drag-and-drop#78]
I seem to be getting this console warning. I have set the following property on my hook:
```
draggable: (el: HTMLElement) => {
      return el.dataset.candrag !== 'false';
},
```
A few items can be dragged, a few items cannot - accordingly they get a `data-candrag` attribute. But none of my items are draggable like this even though console logging the output of `el.dataset.candrag !== 'false'` gives me the exact boolean values. eg: [true, true, false, false] - In this case, first 2 items should be draggable, other two should not. But in the output, none can be dragged

**Comment by sashamilenkovic** [comment]
@valentinoPereira I'd be happy to take a look at a reproduction if you can make one.

**Comment by revenkroz** [comment]
I have the same issue. It appears when you init `dragAndDrop` with existing data and then add to existing data more elements. For example, you init dragAndDrop with empty array and then get data from API to populate the empty array

**Comment by revenkroz** [comment]
This issue appears when you init `dragAndDrop` with `value` instead of `values` in Vue.

In docs:
```
dragAndDrop({
  parent: parentRef,
  value: valueRef
})
```
Should be:
```
dragAndDrop({
  parent: parentRef,
  values: valueRef
})
```

**Comment by psyspeedi** [comment]
@sashamilenkovic Hi! I found the same error when deleting the last element from a group and trying to move the element back. Dragged group inside
draggable group. 

https://github.com/formkit/drag-and-drop/assets/51506019/4ce6719e-cc08-4dbf-b1a3-7a05f8a9dd04

**Comment by sashamilenkovic** [comment]
@psyspeedi This warning appears for quite a few different reasons. Underlying reason being that the number of values passed to the parent do not match the number of children that are rendered. I'm unable to diagnose this from your screen recording, but I'm happy to take a look at a reproduction.
