### ISSUE TITLE
Export `validateDragHandle`

### ISSUE THREAD

**Issue by philipstarkey** [formkit/drag-and-drop#85]
I have a use case where I need to add additional functionality to `handleDragstart` and `handleTouchstart`, while still calling the base handlers. I can do this easily enough (thanks for exposing them in the config and exporting them from the base module!) but when using drag handles, I have no way of determining if the base `handleDragstart`/`handleTouchstart` function has returned immediately because it wasn't the drag handle that triggered the event, or because it's finished successfully.

While it seems possible that a fix for #43 might address this, another immediate solution to my issue would be to export `validateDragHandle()`. That would allow me to verify the event was triggered by the handle before calling my extra code. It doesn't look like `validateDragHandle` is any more internal than any of the other exports, so I'm guessing there isn't any barrier to doing this?

**Comment by sashamilenkovic** [comment]
Great question. I can export this as well. I'll get back to you when I get the chance.

**Comment by sashamilenkovic** [comment]
This is now exported at `v0.2.0`
