### ISSUE TITLE
Drag and drop is jerky sometimes

### ISSUE THREAD

**Issue by aarjithn** [formkit/drag-and-drop#9]
Attached video

https://github.com/formkit/drag-and-drop/assets/10304259/3fd6ee03-97ec-4dcd-9f0f-a386a921d174

https://github.com/formkit/drag-and-drop/assets/10304259/1a9fdedf-926f-4f9c-be51-6efb3d1559c2

**Comment by sashamilenkovic** [comment]
@aarjithn Thank you for filing this issue and the screen recordings. The first issue with the animations plugin has been resolved at v0.0.23. I am going to open a new issue specifically about the second screen recording.

**Comment by sashamilenkovic** [comment]
New issue is filed here https://github.com/formkit/drag-and-drop/issues/22
