### ISSUE TITLE
Replacing element of value array can duplicate the element when dragged

### ISSUE THREAD

**Issue by LofiTurtle** [formkit/drag-and-drop#91]
In Vue, replacing an element of the values array returned by `useDragAndDrop()` and then immediately trying to drag it will result in leaving a copy of the original element in the original location.

To reproduce using the code below:

```vue
<script setup lang="ts">
import { useDragAndDrop } from "@formkit/drag-and-drop/vue";

const [parent, items, updateConfig] = useDragAndDrop([
  {id: 1, label: 'one'},
  {id: 2, label: 'two'},
  {id: 3, label: 'three'},
]);

const updateFirstItem = () => {
  const firstItem = items.value[0];
  const newItem = {id: firstItem.id, label: firstItem.label + ' (edited)'};
  items.value.splice(0, 1, newItem);
  // Uncomment to fix the issue
  // updateConfig({});
}
</script>

<template>
  <ul ref="parent">
    <li v-for="sortKey in items" :key="String(sortKey.id)">
      {{ sortKey.label }}
    </li>
  </ul>
  <button @click="updateFirstItem">
    Update first item
  </button>
</template>
```

1. Click the button to replace the first element with a new object that has `(edited)` appended to its label.
2. Attempt to drag the updated first element.
3. Result is the element getting duplicated, with the element with `(edited)` being dragged, and the original element without `(edited)` being left behind at index 0.

https://github.com/user-attachments/assets/d8c47721-d321-46a4-bda0-0c47bc318aaa

A workaround I found is to call `updateConfig()` after mutating the array with any arguments, such as an empty object. This seems to be enough to cause the mutation to be detected, and dragging works correctly.

**Comment by Lazerproof** [comment]
@LofiTurtle try to call remapNodes(parent.value) instead of updateConfig

**Comment by LofiTurtle** [comment]
That works, thanks. Didn't know that function existed.
